### ISSUE TITLE
bStats not shaded into plugin

### ISSUE THREAD

**Issue by FlippantCactus** [timbru31/SuperWheat#2]
Heyop, using latest paperspigot and getting an issue where mcstats is still being used in your plugin. bStats is where everything is going now quite an easy fix. https://hastebin.com/gizufefuxe.vbs is the error.

**Comment by timbru31** [comment]
Haven't expected that someone would actually use the dev builds 👍   
Can you give build 36 (https://ci.dustplanet.de/job/SuperWheat/36/) a try?

**Comment by FlippantCactus** [comment]
Either a dev build or a plugin 3 years old ;) I'll give it a go
